// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

export default defineConfig({
  datasource: {
    // Gunakan URL utama untuk koneksi database
    url: process.env.DIRECT_URL,
  },
});
